### ISSUE TITLE
Change image slide background size

### ISSUE THREAD

**Issue by JBeater** [MurhafSousli/ngx-gallery#109]
Hi, size of images in gallery is defined like background-size: contain which is fine for pictures of normal or large size. But small pictures are zoomed, and it look bad :( . Is there any way how dont zoom small pictures but keep size. Thank for help :)

**Comment by MurhafSousli** [comment]
Yes you can override the style using CSS, the default style is
```css
.image-item > div {
    background-position: center center;
    background-size: cover;
    width: 100%;
    height: 100%;
}
```
