### ISSUE TITLE
Thumbnail position

### ISSUE THREAD

**Issue by jmbalanag** [MurhafSousli/ngx-gallery#255]
Is there a way to move the thumbnail to the left side most?
![image](https://user-images.githubusercontent.com/7037511/50389503-17de1600-0766-11e9-9d95-3375a07e80f2.png)

**Comment by MurhafSousli** [comment]
You can, but not sure if it works for you

Let's say you used 150px as thumbnail width
```xml
<gallery [items]="items" [thumbWidth]="150"></gallery>
```
Set left to be half of `thumbWidth`
```scss
gallery-thumbs .g-slider {
   left: 75px !important;
}
```
