### ISSUE TITLE
iPhone X issue

### ISSUE THREAD

**Issue by singhot** [MurhafSousli/ngx-gallery#268]
#### What is the expected behavior?

Lightbox should respect iPhone X safe areas

#### What is the current behavior?

Lightbox doesn't respect iPhone X safe areas

#### Which versions are you using for the following packages?

Angular: ^7.2.0
Angular CDK: ^7.2.0
Angular CLI: ^7.2.0
Typescript: ~3.1.6
Gallery: ^4.0.1

#### Is there anything else we should know?

This is my current workaround

```scss
// Fix lighbox display on iphone x
:root {

  lightbox gallery {
    padding: env(safe-area-inset-top) env(safe-area-inset-right) env(safe-area-inset-bottom) env(safe-area-inset-left);

    .g-btn-close {
      padding: env(safe-area-inset-top) env(safe-area-inset-right) env(safe-area-inset-bottom) env(safe-area-inset-left);
    }
  }
}
```

![captura de pantalla 2019-02-04 a la s 17 22 17](https://user-images.githubusercontent.com/47331225/52244502-89e86580-28a3-11e9-9839-77dc4640a36f.png)

![captura de pantalla 2019-02-04 a la s 17 27 21](https://user-images.githubusercontent.com/47331225/52244513-940a6400-28a3-11e9-8fe9-7c4c62e5cac2.png)
