### ISSUE TITLE
Lightbox Fluid width / height 100%

### ISSUE THREAD

**Issue by Jscott388** [MurhafSousli/ngx-gallery#43]
Setting the width and height too 100% doesn't work. I would like the lightbox to be full screen.

Using the fluid generator, light box will not appear.

**Comment by MurhafSousli** [comment]
Hi @Jscott388 the fluid style in the generator does not work for the lightbox, in fact, the generator has some bugs at the moment, will fix them when I get the time.
For the now the lightbox uses fixed size, but I believe it is possible to make it fluid with some CSS
Try these:
```scss
.g-overlay {
   width: 100%;
   height: 100%;
}
gallery-lightbox {
   height: 100%;
   max-width: unset;
   max-height: unset;
}
gallery {
   height: 100%;
   display: flex;
}
gallery-main { 
   height: 100%;
   width: 100%;
}
.g-container {
   height: 100%;
   width: 100%;
}
```
I just applied these in the browser and got a fluid lightbox, if it didn't work right away, add `!important` on them
