### ISSUE TITLE
[FR] Allow Custom CSS Styling for Next/Prev Button

### ISSUE THREAD

**Issue by quinnjr** [MurhafSousli/ngx-gallery#437]
#### What is the expected behavior?
I would expect that I should be able to style the buttons for the next/previous slides based on my site's CSS styles.

#### What is the current behavior?
I cannot apply styles to the buttons for the next/previous slide buttons targeting `.g-nav-next` or `.g-nav-prev`.

#### What is the use-case or motivation for changing an existing behavior?
Allows users of the library to further customize their installation to match their site's design.

#### Which versions are you using for the following packages?

Angular: 13.3.2
Angular CDK: 13.3.2
Angular CLI: 13.3.2
Typescript: ~4.4.4
Gallery: 6.0.1

**Comment by Sourav-Agarwalla** [comment]
Can we have this navigation icons in black color as well? 
~as its a SVG format, I'm not able to override the color of it. Can you please help if its possible?

**Comment by quinnjr** [comment]
EG:

In my current application, I'd like the Next/Prev buttons to use my theme's primary color:

```scss
.g-nav-next, 
.g-nav-prev {
  background-color: $primary;
}
```

However, upon loading the application and compiling the style sheet, the coloring is not set on the buttons.

**Comment by MurhafSousli** [comment]
You need to add these styles in your global CSS file `style.scss`

```scss
.g-nav-next, 
.g-nav-prev {
  background-color: yellow;

  svg path {
    fill: red;
  }
}
```
Check it here https://stackblitz.com/edit/ngx-gallery-zpnbqa?file=src%2Fstyles.scss
