### ISSUE TITLE
Need the possibility to overwrite the black thumbs background with another color

### ISSUE THREAD

**Issue by awunnenb** [MurhafSousli/ngx-gallery#629]
#### What is the expected behavior?

I need the possibility to overwrite the black thumbs background with another color. Is this already possible?

#### Which versions are you using for the following packages?

Angular CLI: 19.0.7
Angular/cdk: 19.0.5
ng-gallery: 12.0.0
Node: 22.13.0
Package Manager: npm 10.9.2
OS: linux x64

**Comment by MurhafSousli** [comment]
Add this in the global styles

```css
gallery-thumb {
  background-color: white !important;
}
```
