### ISSUE TITLE
Image are cropped by zooming/fitting

### ISSUE THREAD

**Issue by gusarov** [MurhafSousli/ngx-gallery#80]
Some images becomes partially zoomed and part of content is not seen. Is it possible to disable automatic zooming and just show more neighbors of image in case when image size differs from gallery size too much?

**Comment by MurhafSousli** [comment]
Just use pure CSS
```scss
::ng-deep {
  image-item div {
    background-size: contain !important; 
    background-repeat: no-repeat;
  }
}
```
[stackblitz demo](https://stackblitz.com/edit/ngx-gallery-3gve8c?file=app%2Fapp.component.scss)

**Comment by pharindoko** [comment]
Hey Murhaf,
thanks for this greate library and for the many useful updates.
But.... :)
this doesn`t work anymore since the new 3.02 has been released:-\

**Comment by MurhafSousli** [comment]
@pharindoko in v3.0.2, use the following
```scss
::ng-deep {
  gallery-image .g-image-item {
    background-size: contain; 
    background-repeat: no-repeat;
  }
}
```
